<?php

class CampFields
{
    public function registerFields()
    {
        if (!function_exists('acf_add_local_field_group')) return;

        acf_add_local_field_group(array(
            'key' => 'group_65211c0323ddf',
            'title' => 'Camp Data',
            'fields' => array(
                array(
                    'key' => 'field_65211c0aab7c9',
                    'label' => 'Name',
                    'name' => 'name',
                    'type' => 'text',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placeholder' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_652121ead2b94',
                    'label' => 'Location',
                    'name' => 'location',
                    'type' => 'text',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placeholder' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_65211d210c326',
                    'label' => 'Postcode',
                    'name' => 'postcode',
                    'type' => 'text',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placeholder' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_65211d32f642f',
                    'label' => 'Opening Time',
                    'name' => 'opening_time',
                    'type' => 'time_picker',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'g:i a',
                    'return_format' => 'g:i a',
                ),
                array(
                    'key' => 'field_65211d5af6430',
                    'label' => 'Closing Time',
                    'name' => 'closing_time',
                    'type' => 'time_picker',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'g:i a',
                    'return_format' => 'g:i a',
                ),
                array(
                    'key' => 'field_65211d8ae1cc4',
                    'label' => 'Extended Opening Time',
                    'name' => 'extended_opening_time',
                    'type' => 'time_picker',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'g:i a',
                    'return_format' => 'g:i a',
                ),
                array(
                    'key' => 'field_65211d7ae1cc3',
                    'label' => 'Extended Closing Time',
                    'name' => 'extended_closing_time',
                    'type' => 'time_picker',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'g:i a',
                    'return_format' => 'g:i a',
                ),
                array(
                    'key' => 'field_65211d9be1cc5',
                    'label' => 'Opening Months',
                    'name' => 'opening_months',
                    'type' => 'checkbox',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'Feb' => 'Feb',
                        'Easter' => 'Easter',
                        'May' => 'May',
                        'Summer' => 'Summer',
                        'Oct' => 'Oct',
                        'Christmas' => 'Christmas',
                    ),
                    'allow_custom' => 0,
                    'default_value' => array(),
                    'layout' => 'vertical',
                    'toggle' => 0,
                    'return_format' => 'value',
                    'save_custom' => 0,
                ),
                array(
                    'key' => 'field_65211e2fc118f',
                    'label' => 'Min Age',
                    'name' => 'min_age',
                    'type' => 'number',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'placeholder' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_65211e6887836',
                    'label' => 'Max Age',
                    'name' => 'max_age',
                    'type' => 'number',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'placeholder' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_65w1ad210c326',
                    'label' => 'Age Text',
                    'name' => 'age_text',
                    'type' => 'text',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'placeholder' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_652121be4d272',
                    'label' => 'Childcare vouchers / Tax free',
                    'name' => 'childcare_vouchers_tax_free',
                    'type' => 'true_false',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
                array(
                    'key' => 'field_6521221dbe044',
                    'label' => 'URL',
                    'name' => 'url',
                    'type' => 'url',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_65212276e348a',
                    'label' => 'Logo',
                    'name' => 'logo',
                    'type' => 'image',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'medium',
                    'library' => 'all',
                ),
                array(
                    'key' => 'field_653df73268328',
                    'label' => 'Latitude',
                    'name' => 'latitude',
                    'type' => 'number',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'placeholder' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_653df73e68329',
                    'label' => 'Longitude',
                    'name' => 'longitude',
                    'type' => 'text',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'placeholder' => '',
                    'maxlength' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'camps',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        ));
    }
}
